### ISSUE TITLE
COLT path is not specified, please enter the path

### ISSUE THREAD

**Issue by AttilaSATAN** [code-orchestra/colt-sublime3-plugin#1]
I got an error while try to "Run with COLT" and "Start with COLT" commands on index.html of my project. 
I'm using Linux Mint.
I have installed COLT via Package Control.

**Comment by makc** [comment]
Not really an error, it just does not know where did you install COLT. So it asks for a path.

**Comment by makc** [comment]
To be clear: plugin itself only talks to COLT and pulls info back to sublime; the COLT itself is standalone app that needs to be installed separately. I'm not sure about linux build status, we had no linux build last time I checked, but people were working on it.
