### ISSUE TITLE
Does COLT watching for new files?

### ISSUE THREAD

**Issue by webuniverseio** [code-orchestra/colt-sublime3-plugin#12]
Please take a look at the following video, there are no js completions for file which was added after the start of colt server: http://youtu.be/5Knd0oaSCe4

Please let me know if you need a sample project.

**Comment by makc** [comment]
Sample project is always good idea.

**Comment by webuniverseio** [comment]
Sent you a sample project code. Following [video](http://youtu.be/LnnYwArZb14) shows the steps I'm taking to find the issue.
If you don't want to install [bower](http://bower.io/), after start of the COLT server you can copy 'squire_move_and_rename_me_withing_bower_components_after_start_of_a_colt_server'  inside  'bower_components' folder and rename it to 'squire'. Please let me know if you have any questions.

Thank you.

**Comment by makc** [comment]
Hey, I have checked this sample. It appears that we have this bug when empty functions do not get code completion hooks. So, to work around this right now, simply put anything in the function, e.g. "hello"; or var foo = 1; and we shall fix this in the new build.

**Comment by webuniverseio** [comment]
I see. Good to know, thank you.

**Comment by makc** [comment]
This should have been fixed in [recent build](https://twitter.com/code_orchestra/status/428153311993544704), feel free to download and try again.

**Comment by webuniverseio** [comment]
Yey, COLT developers are the best. Thank you!
