### ISSUE TITLE
File size of workingset.xml might grow very fast

### ISSUE THREAD

**Issue by webuniverseio** [code-orchestra/colt-sublime3-plugin#4]
Hi, below you can see output of my workingset.xml. Probably each time I add another project slashes in path for previous projects double it's size.

```
<workingset openRecent='true'>
  <project path='C:\Program Files (x86)\COLT\projects\js\balls\autogenerated.colt' />
  <project path='C:\\Program Files (x86)\\COLT\\projects\\js\\balls\\autogenerated.colt' />
  <project path='C:\\Program Files (x86)\\COLT\\projects\\js\\balls\\autogenerated.colt' />
  <project path='C:\\\\Program Files (x86)\\\\COLT\\\\projects\\\\js\\\\balls\\\\autogenerated.colt' />
  <project path='C:\\\\Program Files (x86)\\\\COLT\\\\projects\\\\js\\\\balls\\\\balls.colt' />
  <project path='C:\\\\Program Files (x86)\\\\COLT\\\\projects\\\\js\\\\balls\\\\autogenerated.colt' />
</workingset>
```

Probably worse to mention that I'm using latest version of plugin which is available through Package control. Os is windows 8.1.

**Comment by makc** [comment]
Idk man, as I said before https://github.com/code-orchestra/colt-sublime3-plugin/commit/791c5408ba41336d16beb7f904fee0877723fd43 fixes this. Try to remove sublime plugin and then install again, rather than update?

**Comment by webuniverseio** [comment]
Yep, that did the trick. Probably a bug in PM because it was telling me that all plugins were updated. Sorry.
