### ISSUE TITLE
How to connect existing colt project to sublime?

### ISSUE THREAD

**Issue by webuniverseio** [code-orchestra/colt-sublime3-plugin#5]
Probably the last issue I have at the moment: I would like to create a project in COLT with particular settings, then from sublime run colt with that project. However when I run colt from sublime it always opens new colt window, creates auto-generated project and connects to it. If then I'm trying to switch to another project (by opening project or opening recent project) sublime looses connection. Is there any way to preserve connection?
http://www.youtube.com/watch?v=PeMljduJh-w

**Comment by makc** [comment]
rename or copy existing colt file to "autogenerated.colt"?

**Comment by webuniverseio** [comment]
I see now. It is not very obvious, though. Sounds more like a workaround. Well it did the trick, feel free to close the ticket. And thank you for all your help makc, now I'm feeling more confident about how to use the program. I'll play more with it and try to convince other developers in my company to use it.

**Comment by makc** [comment]
The idea was that you create the project from sublime, then alter the settings in colt and save. Next time sublime would pick it up and only change the main file (if anything).
