### ISSUE TITLE
Starting livecoding session seems to be sluggish

### ISSUE THREAD

**Issue by webuniverseio** [code-orchestra/colt-sublime3-plugin#8]
Please take a look at the following video. First I'm trying to lunch colt from sublime, but doesn't look like completions are being catched. Then I'm re-lunching livecoding session manually - console starts to work, but html and js completions still don't. Then after reload from sublime - js starting to work. Then, after number of various reloads, html starts to work without any clue why. It might be that I misunderstand how it all should work, can you please clarify if it is a bug or if I'm doing something wrong?

http://www.youtube.com/watch?v=EQ3UQFfpbXk&feature=youtu.be

Thank you.

**Comment by makc** [comment]
Apparently there is some failure during session start, but I can't understand why before I reproduce this on my side. So I am going to need sample project.

**Comment by webuniverseio** [comment]
I feel that bug will be tricky. Here are my thoughts - if your project has bunch of scripts, css, images, other assets in the same folder where you have your index.html, then it takes colt longer (depending on size and number of assets) to launch. After launch it also takes time to establish connection (I was testing by adding/removing js files from my working folder).

Also another thing I notices - even though I defined certain files and folders to be excluded from project they are still copied in '.colt\storage\cd7d47fb\out\' folder - not sure if might affect connection performance, but thought I should note that.

Also I noticed that it takes time to apply transformations even for small files, not sure if anything can be done to optimize that though: http://www.youtube.com/watch?v=bR7H7s2rdHs&feature=youtu.be.

For my tests I'm using dojo library (which is huge, but I'm using only one 'dojo' folder from whole framework). I'll play more with that and get back with my observations tomorrow or on Wednesday.

**Comment by webuniverseio** [comment]
@makc if anything can be done about following it will definitely speed up connection establishment (and reduce time spent for transformations):

> Also another thing I noticed - even though I defined certain files and folders to be excluded from project they are still copied in '.colt\storage\cd7d47fb\out\' folder - not sure if might affect connection performance, but thought I should note that.

**Comment by makc** [comment]
Since last COLT revision broke nodejs compatibility, we'll be definitely looking into this area. However, nothing would help us more than sample project that has problems starting up.

**Comment by webuniverseio** [comment]
Sure, should I send it to that email - nikishin@codeorchestra.com?

**Comment by makc** [comment]
Nah, that guy has left. Send to [me](http://makc3d.files.wordpress.com/2008/10/gothicemail.gif) instead.

**Comment by webuniverseio** [comment]
Sent you a sample projects. When I run colt from sublime text 3 (Windows 8.1) it takes ~1.5 minutes to live coding establish connection for html updates. Hopefully you'll be able to reproduce the issue. Please don't worry about javascript files, they seem to start getting updates as soon as I restart from colt after start of a session. The issue is only related to connection and html updates.

Thank you

**Comment by makc** [comment]
This project has no problems with colt dev version / ST3 / mac. Either you use outdated colt, or we have windows-only problem. I will test on windows and let you know.

**Comment by webuniverseio** [comment]
You are right about outdated version, after I installed v1.2.6 colt started to fly! Insane, I love it so much!
One thing I want to note - there is no way for user to tell if colt was updated. So either on site you need to specify version number next to download button or notify users in some other way.

Thank you

**Comment by makc** [comment]
Yep, no luck seeing this on windows, either
